### ISSUE TITLE
[Feature request]: Rotation of Insta360 Footage

### ISSUE THREAD

**Issue by KwadLife** [gyroflow/gyroflow#95] opened 2022-02-05 22:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Insta360 cams can be mounted in varios positions. In Pro-Mode this leads sometime to a vertical image would be great to rotate the preview image and export image so you dont need to do it in post.
![Insta360 Footage](https://user-images.githubusercontent.com/44123988/152660868-e3e991fd-02db-40b3-8b7e-2438044fd480.PNG)

**Comment by sweebee** [comment] 2022-02-05 23:47
looks like a bug, check my issue #59

**Comment by AdrianEddy** [comment] 2022-02-06 12:23
Duplicate of #59

**Closed by AdrianEddy** 2022-02-06 12:23 UTC
Labels: enhancement

**Comment by KwadLife** [comment] 2022-02-09 10:55
fixed
