### ISSUE TITLE
Limiting the maximum Dynamic Zoom level?

### ISSUE THREAD

**Issue by MR444** [gyroflow/gyroflow#709] opened 2023-08-15 12:28 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hi all,
is there a way to limit the maximum zoom level when dynamic zoom is activated? I could imagine having a parameter in percentage that sets the minimum and maximum zoom level, e.g. 110% min to 140% max.

With my Gopro Hero 8 I often have the problem that dynamic zoom zooms much to much when I do flips or loops.
With my Runcam Thumb Pro V2 I have that problem also during normal flights.
Thank you.

**Comment by AdrianEddy** [comment] 2023-08-15 12:31
Duplicate of #658, you can do it mostly by using the 3 smoothness sliders, explained in the linked issue

**Closed by AdrianEddy** 2023-08-15 12:31 UTC
Labels: enhancement
