### ISSUE TITLE
[Bug]: Slow on Intel Mac

### ISSUE THREAD

**Issue by sweebee** [gyroflow/gyroflow#85] opened 2022-02-05 18:52 UTC
### Gyroflow version

v1.0.0-rc1

### What operating system are you using?

MacOS 12.1

### What GPU are you using?

AMD Radeon Pro 5300M

### What happened?

I have a 2019 16 inch MacBook with a 2,6 GHz 6-Core Intel Core i7 CPU and AMD Radeon Pro 5300M GPU. 

a 3.5 minute video takes around 20 minutes to export, seems quite long to me. It doesn't matter if I turn on/off "Use GPU encoding".

I'm stabilizing an Insta 360 Go2 2.7K video and exporting it to h.264 at 2704 x 1540.

**Comment by AdrianEddy** [comment] 2022-02-08 04:52
Duplicate of #74, working on it

**Closed by AdrianEddy** 2022-02-08 04:52 UTC
Labels: bug
