### ISSUE TITLE
bug at 7:00

### ISSUE THREAD

**Issue by bygiants** [gyroflow/gyroflow#936] opened 2024-12-08 16:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

Win 10

### What GPU are you using?

nVidia

### What happened?

Between 6:50 and 7:00 the image becomes pixelated :

Example 1
![Liverdun_03_bug](https://github.com/user-attachments/assets/38da6f44-533a-4f72-bb21-2e320dea3c94)
![Liverdun_03_OK](https://github.com/user-attachments/assets/e3fb2e61-f07b-49b7-a421-ddc11ecef1a9)

Example 2
![Stock_01_bug](https://github.com/user-attachments/assets/dada1ae9-4eec-403f-85fa-6c87ff5b2fbb)
![Stock_01_OK](https://github.com/user-attachments/assets/5a135605-64ea-4201-b6eb-7d999dc72c92)
from the video : 
https://www.youtube.com/watch?v=z358wOsBDAI&t=321s

lens profile : dji O3 
video speed : 33 %
h.265 - 200 MB/s

Hope that helps.
Please let me know if you need more info.

Thanks for sharing your work.
Have a great day.

Vincent Berger
bergervincent.fr

**Comment by AdrianEddy** [comment] 2024-12-13 21:04
try exporting with "GPU Decoding" (in Advanced)" disabled

**Comment by AdrianEddy** [comment] 2024-12-21 15:03
This should already be fixed in the dev build https://gyroflow.xyz/devbuild/ and if it's not fixed automatically, it's caused by the video decoder which is outside of my control. Exporting with GPU Decoding disabled should fix this

**Closed by AdrianEddy** 2024-12-21 15:03 UTC
Labels: bug
