### ISSUE TITLE
[Bug]: FireFly xLite csv file not supported

### ISSUE THREAD

**Issue by MarkfpvMark** [gyroflow/gyroflow#98] opened 2022-02-05 23:09 UTC
### Gyroflow version

v1

### What operating system are you using?

Os Mojave 10.14.6 

### What GPU are you using?

Intel Iris

### What happened?

![Schermata 2022-02-06 alle 00 05 23](https://user-images.githubusercontent.com/99101644/152661964-60056cd8-600a-4ca6-bcdd-4691b67b5a19.png)

hello,
when i try to load the csv file from the firefly xLite camera this message showup, is impossible load the gyro data.

**Comment by ElvinC** [comment] 2022-02-06 05:59
Could you attach an example file?

**Comment by ElvinC** [comment] 2022-02-06 06:04
Duplicate of https://github.com/gyroflow/gyroflow/issues/98

**Closed by ElvinC** 2022-02-06 06:04 UTC
Labels: bug

**Comment by MarkfpvMark** [comment] 2022-02-06 10:08
Sure here the csv file link download
[
](https://we.tl/t-3kjAILb5jH)
