### ISSUE TITLE
[ubuntu] GPU encoding not possible

### ISSUE THREAD

**Issue by nightflasher** [gyroflow/gyroflow#246] opened 2022-02-25 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc4

### What operating system are you using?

ubuntu 22.04.4 LTS

### What GPU are you using?

AMD ATI Radeon R7 530 | INTEL UHD 620

### What happened?

not possible to export using GPU rendering (x264 & x265), no gpu rendering with ProRes
![Bildschirmfoto von 2022-02-25 16-53-32](https://user-images.githubusercontent.com/3342605/155747613-8d55e328-a05d-48ad-9893-2d46321c10ed.png)

### Relevant log output

```shell
15:53:25 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Converting from NV12 to VAAPI_VLD
[swscaler @ 0x7f1ab366a1c0] 0bpp not supported by yuv2rgb
[swscaler @ 0x7f1ab366a1c0] vaapi_vld is not supported as output pixel format
[aac @ 0x7f1ab237a080] Qavg: nan
15:53:45 [DEBUG] (2) gyroflow::rendering: ffmpeg_hw::supported_gpu_backends: ["vdpau", "cuda", "vaapi", "qsv"]
15:53:45 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: [dec] codec type AV_HWDEVICE_TYPE_CUDA 0
[AVHWDeviceContext @ 0x7f1ab000a080] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x7f1ab000a080] Could not dynamically load CUDA
15:53:45 [DEBUG] (2) gyroflow::rendering: Failed to create specified HW device: AV_HWDEVICE_TYPE_CUDA

15:53:45 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: [dec] codec type AV_HWDEVICE_TYPE_VAAPI 1
15:53:45 [DEBUG] (2) gyroflow::rendering: Selected HW backend AV_HWDEVICE_TYPE_VAAPI (vaapi) with format Some(AV_PIX_FMT_VAAPI_VLD)

15:53:45 [DEBUG] (2) gyroflow::rendering: proc.gpu_device: Some("vaapi")
15:53:45 [DEBUG] (2) gyroflow::rendering: Possible encoders with AMD: [("libx265", false)]
15:53:45 [DEBUG] (2) gyroflow::rendering: video_codec: Some("libx265"), processing_order: PreConversion
15:53:45 [DEBUG] (2) gyroflow::rendering: start_us: 0, render_duration: 271840, render_frame_count: 6796
15:53:45 [DEBUG] (2) gyroflow::rendering::ffmpeg_processor: Codec formats: [YUV420P, YUVJ420P, YUV422P, YUVJ422P, YUV444P, YUVJ444P, GBRP, YUV420P10LE, YUV422P10LE, YUV444P10LE, GBRP10LE, YUV420P12LE, YUV422P12LE, YUV444P12LE, GBRP12LE, GRAY8, GRAY10LE, GRAY12LE]
15:53:47 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Hardware transfer formats from GPU: Some([NV12, BGRA, ARGB, RGBA, ABGR, BGRZ, ZRGB, RGBZ, ZBGR, X2RGB10LE, GRAY8, YUYV422, UYVY422, YUV420P, YUV420P, YUV411P, YUV422P, YUV440P, YUV444P, P010LE])
15:53:47 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Converting from NV12 to YUV420P
15:53:47 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type: None, encoder_pixel_format: Some(YUV420P)
15:53:47 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Setting output pixel format: YUV420P, color range: JPEG
15:53:47 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type None
```

**Comment by AdrianEddy** [comment] 2022-02-25 16:45
Please attach full log

**Comment by nightflasher** [comment] 2022-02-25 22:18
okay...just added the directory listing of lib - some files are missing
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8145165/gyroflow.log)

**Comment by wkaichung** [comment] 2022-04-03 17:10
me too! i am using Macbook Pro M1 max. Cant use GPU to export neither. same problem. The export time of a 7min clip are using 11hours to export!!!!!

**Comment by AdrianEddy** [comment] 2022-04-03 17:19
@wkaichung
Please provide log from latest dev build https://gyroflow.xyz/devbuild/?autodownload
1. Open terminal
2. Right click on Gyroflow and Open package contents -> Contents -> MacOS
3. Drag gyroflow into terminal and click enter
then after you start rendering you can cancel and close the app
gyrolow.log should be created next to gyroflow file. If it doesn't just copy me the contents of the terminal

**Comment by szebedy** [comment] 2022-05-29 11:26
Hello, I'm having the same issue with my AMD RX 550 GPU on Windows 11. The problem is that the encoder is using the CUDA library from Nvidia, which only works with Nvidia GPUs. The solution could be an alternative encoding method which does not use CUDA. I attached the error message and my log file.

![error](https://user-images.githubusercontent.com/23255730/170865482-5f3fe1f3-479c-47e4-af66-366d8f660a34.png)

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8793218/gyroflow.log)

**Comment by macrokernel** [comment] 2022-06-16 16:29
I am having the same issue on Linux Mint 20.2 Cinnamon, kernel version: 5.13.0-41-generic https://github.com/gyroflow/gyroflow/issues/46~20.04.1-Ubuntu running on AMD Ryzen 5 4600H with Radeon Graphics (integrated graphics). 

![image](https://user-images.githubusercontent.com/9429051/174119953-a1f7fccd-22c7-40cf-a351-bf751c763cc3.png)

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8920764/gyroflow.log)

**Comment by AdrianEddy** [comment] 2022-11-18 02:30
Does this still happen in latest dev build? https://gyroflow.xyz/devbuild/?autodownload

If yes, please post the log

**Comment by mituritsyn** [comment] 2022-11-18 08:29
> Does this still happen in latest dev build? https://gyroflow.xyz/devbuild/?autodownload
> 
> If yes, please post the log

Ubuntu 20.04, AMD Ryzen 5 2600, Radeon RX580
ProRes, X264,x264 wo GPU encoding
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10039498/gyroflow.log)
![image](https://user-images.githubusercontent.com/15355893/202656099-99dc2090-660e-49b2-8d73-19900c598b14.png)
after picking VAAPI

![image](https://user-images.githubusercontent.com/15355893/202656131-a39bbca0-b303-4607-b653-b7ac9dd35740.png)

**Comment by AdrianEddy** [comment] 2022-11-18 16:39
@mituritsyn thanks for the log, I made some updates, could you please check in the latest one? https://gyroflow.xyz/devbuild/?autodownload
Please also post a log

**Comment by macrokernel** [comment] 2022-11-18 16:47
[log.txt](https://github.com/gyroflow/gyroflow/files/10043159/log.txt)

**Comment by mituritsyn** [comment] 2022-11-18 20:34
> @mituritsyn thanks for the log, I made some updates, could you please check in the latest one? https://gyroflow.xyz/devbuild/?autodownload Please also post a log

**AppImage:**
same error, but after chosing VAAPI UI blinks and I see same popup :
![image](https://user-images.githubusercontent.com/15355893/202796171-59297a29-5c58-4445-a6c3-fed4e775e7b1.png)

if I choose CPU then this appers:

![image](https://user-images.githubusercontent.com/15355893/202796298-f2410d22-01e0-4ca6-a640-e175ca04456b.png)

moreover, sync points not showing anymore:

![image](https://user-images.githubusercontent.com/15355893/202796579-ab80c971-c8d6-41ba-9a7b-eb8ab2389843.png)

**Tar.Gz**
crashes after choosing CPU
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10044663/gyroflow.log)
[19518737-f690-4b40-3f1c8d8e-4835b76b.zip](https://github.com/gyroflow/gyroflow/files/10044664/19518737-f690-4b40-3f1c8d8e-4835b76b.zip)

**Comment by AdrianEddy** [comment] 2022-11-19 04:17
How about now? (same download link)

**Comment by mituritsyn** [comment] 2022-11-19 06:29
> How about now? (same download link)

seems to be fixed

**Comment by mituritsyn** [comment] 2022-11-19 06:47
> seems to be fixed

I apologize, in a hurry, almost to the end of the rendering an error appears, perhaps it is another problem, but still:
h265
![image](https://user-images.githubusercontent.com/15355893/202838374-7cc5e06b-a749-4c11-b457-ba84d9b3fdc5.png)
h264
![image](https://user-images.githubusercontent.com/15355893/202838467-58dd00e7-1968-4692-b30c-714bbebc4495.png)
and then
![image](https://user-images.githubusercontent.com/15355893/202838412-f6c929e0-ff93-493f-82ed-ad137cf62896.png)

ProRes
![image](https://user-images.githubusercontent.com/15355893/202838497-d1093007-b0a3-450d-89e7-a4fcf603bc94.png)
log attached
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10046328/gyroflow.log)

**Comment by AdrianEddy** [comment] 2022-11-19 17:11
Hmm can you try exporting just 1 second from the video? (Just set a short trim range)

ProRes doesn't support hardware acceleration except M1 macs

**Comment by mituritsyn** [comment] 2022-11-19 18:50
> Hmm can you try exporting just 1 second from the video? (Just set a short trim range)
> 
> ProRes doesn't support hardware acceleration except M1 macs

up to approximately 15 frames exporting successfully
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10047740/gyroflow.log)

**Comment by nightflasher** [comment] 2022-11-19 21:08
[gyroflow_gh886_21frames.log](https://github.com/gyroflow/gyroflow/files/10047948/gyroflow_gh886_21frames.log)
![Bildschirmfoto vom 2022-11-19 22-04-29](https://user-images.githubusercontent.com/3342605/202871608-90b55c39-4c17-4cac-83a0-2cdde6615ec0.png)
tried 21 frames, like mituritsyn with no luck

**Comment by AdrianEddy** [comment] 2022-11-19 21:16
@nightflasher your issue is a different reason, what does `vainfo` say when you type it into terminal?

**Comment by AdrianEddy** [comment] 2022-11-19 22:34
@mituritsyn How about now?

**Comment by nightflasher** [comment] 2022-11-19 23:20
`libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
`
but with DRI_Prime it doesn't change, so no AMD GPU acceleration?

**Comment by AdrianEddy** [comment] 2022-11-19 23:23
Hmm so in your case, we need to tell VAAPI to use the AMD card rather than Intel, right? I think that flag is `-hwaccel_device 1` in FFmpeg CMD line?

**Comment by nightflasher** [comment] 2022-11-19 23:26
command: DRI_PRIME=1 ffmpeg -hwaccels (same without DRI_PRIME=1)

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hardware acceleration methods:
vdpau
cuda
vaapi
qsv
drm
opencl

**Comment by mituritsyn** [comment] 2022-11-20 07:34
> @mituritsyn How about now?

Now it works. But only at half speed. Was about 40fps, now only 20fps

**Comment by AdrianEddy** [comment] 2022-11-20 10:29
@mituritsyn I believe before it wasn't encoding properly, because the HW frame pool was set to 20 frames and the frames were never freed, so it only encoded 20 frames and then it silently continued with errors until the end. You could manually time how long it takes ffmpeg to transcode the same video and how long it takes in gyroflow, should be similar. Could you confirm one last time that the encoding is working in the latest dev build? I made some changes


@nightflasher Please download latest dev build ( https://gyroflow.xyz/devbuild/?autodownload ) and let me know these:
1. output from `DRI_PRIME=0 vainfo`
2. output from `DRI_PRIME=1 vainfo`
3. GPU encoding in gyroflow using H264/AVC
4. GPU encoding in gyroflow using H265/HEVC, but adding `-hwaccel_device 1` to the "Custom encoder options"
5. Is #405 still an issue or is it fixed?

![image](https://user-images.githubusercontent.com/3849067/202897144-216e9b69-7d6c-4aa3-9d1d-559da500e59f.png)

**Comment by nightflasher** [comment] 2022-11-20 12:13
1 & 2 => attached TXT
3. same as before
4. is working, but slow (about 5-10 fps)
5. i think so. can be closed (already working in stable 1.3.0 gh816)

![Bildschirmfoto vom 2022-11-20 13-11-01](https://user-images.githubusercontent.com/3342605/202901115-cb2a0aef-3453-4660-ba5c-6cabf7184c6f.png)
[vainfo_both.txt](https://github.com/gyroflow/gyroflow/files/10049609/vainfo_both.txt)

**Comment by AdrianEddy** [comment] 2022-11-20 14:37
4. Could you please send me the gyroflow.log after rendering with `-hwaccel_device 1`?

**Comment by nightflasher** [comment] 2022-11-20 15:07
here you go
[gyroflow_github.log](https://github.com/gyroflow/gyroflow/files/10049990/gyroflow_github.log)

**Comment by nightflasher** [comment] 2022-11-20 16:25
But i'm trying to use the dedicated AMD GPU (specs in the first post)

**Comment by AdrianEddy** [comment] 2022-11-20 16:39
I know, please try again in latest version, i fixed one more bug. Use `-hwaccel_device 1`

**Comment by macrokernel** [comment] 2022-11-20 17:30
![image](https://user-images.githubusercontent.com/9429051/202916745-1cb7bcc1-1280-43c6-9c02-67d9e3af1b09.png)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10050300/gyroflow.log)

**Comment by AdrianEddy** [comment] 2022-11-20 18:16
@macrokernel does VAAPI in ffmpeg work for you? something like `ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i INPUT_FILE.mp4 -vf "format=nv12,hwupload" -c:v h264_vaapi OUTPUT_FILE.mp4`?
What does `vainfo` return on your device? Maybe also try setting `-hwaccel_device /dev/dri/renderD128` in gyroflow encoder params.

Some more info here https://trac.ffmpeg.org/wiki/Hardware/VAAPI

**Comment by nightflasher** [comment] 2022-11-20 19:06
found something "maybe useful'
see attached file
[vainfo_libvadriver.txt](https://github.com/gyroflow/gyroflow/files/10050475/vainfo_libvadriver.txt)

**Comment by mituritsyn** [comment] 2022-11-20 19:51
> @mituritsyn Could you confirm one last time that the encoding is working in the latest dev build? I made some changes

I couldn't. Doesn't work again
![image](https://user-images.githubusercontent.com/15355893/202922947-99905eb0-b72b-4a88-960b-a6014d37e0de.png)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10050565/gyroflow.log)

**Comment by mituritsyn** [comment] 2022-11-20 20:54
> @macrokernel does VAAPI in ffmpeg work for you? something like `ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i INPUT_FILE.mp4 -vf "format=nv12,hwupload" -c:v h264_vaapi OUTPUT_FILE.mp4`?

done wo errors:
`frame= 3575 fps= 23 q=-0.0 Lsize=  395219kB time=00:00:59.62 bitrate=54298.4kbits/s speed=0.384x    
video:394217kB audio:935kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.016936%
[aac @ 0x55cdac43a140] Qavg: 379.303
`
> What does `vainfo` return on your device? 

`$ vainfo
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 22.0.5 for AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.0-53-generic)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
`
>Maybe also try setting `-hwaccel_device /dev/dri/renderD128` in gyroflow encoder params.
 
same error
 
![image](https://user-images.githubusercontent.com/15355893/202925611-1b7fea30-a8fc-4dad-8c80-36cb5f7df0c7.png)

**Comment by AdrianEddy** [comment] 2022-11-20 20:58
> I couldn't. Doesn't work again

Right, sorry, I made some bad changes, please try gh895 in ~10 minutes (status here https://github.com/gyroflow/gyroflow/actions/runs/3509685259)

**Comment by nightflasher** [comment] 2022-11-20 21:23
i found this "clinfo" and have the output for you
[clinfo.txt](https://github.com/gyroflow/gyroflow/files/10050740/clinfo.txt)

**Comment by mituritsyn** [comment] 2022-11-20 21:29
> > I couldn't. Doesn't work again
> 
> Right, sorry, I made some bad changes, please try gh895 in ~10 minutes (status here https://github.com/gyroflow/gyroflow/actions/runs/3509685259)

last build is ok. btw it was almost 25% faster than this one)) https://github.com/gyroflow/gyroflow/issues/246#issuecomment-1321060991

**Comment by AdrianEddy** [comment] 2022-11-20 22:11
> last build is ok. btw it was almost 25% faster than this one)) 

Cool, thanks

@nightflasher how about you in latest build? Does it work? By default or with `hwaccel_device`?

**Comment by nightflasher** [comment] 2022-11-20 22:26
no, neither off them. i have now installed ffmpeg5 (https://launchpad.net/~savoury1/+archive/ubuntu/ffmpeg5) and i have successfully rendered "ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/card0 -i test.mp4 -vf "format=nv12,hwupload" -c:v h264_vaapi test_new.mp4" with 35fps (but it's the intel graphics card). i think my dedicated amd isn't installed correctly.

i also have another terminal output with this command: **DRI_PRIME=1 LIBVA_DRIVER_NAME=radeonsi vainfo** 
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.16 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 23.0.0-devel for AMD Radeon R5 M445 Series (iceland, LLVM 15.0.4, DRM 3.42, 5.15.0-41-generic)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

**Comment by AdrianEddy** [comment] 2022-11-20 22:29
Did you try setting `-hwaccel_device /dev/dri/card0` in Gyroflow? Can you show me the log?

**Comment by nightflasher** [comment] 2022-11-20 22:35
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10050865/gyroflow.log)
this didn't work at all.

**Comment by AdrianEddy** [comment] 2022-11-20 22:58
@nightflasher looks like your Intel card only supports H264/AVC encoding, not HEVC.
AMD may support HEVC, but doesn't look like it's detected/installed properly

Can you try again with H264/AVC?

You can select `Device for processing` under Advanced panel and select `[wgpu] AMD Radeon R5 M445 Series (RADV ICELAND) (Vulkan)`. This way Intel card will be used to encode, and AMD card will be used to process (stabilize) pixels

**Comment by macrokernel** [comment] 2022-11-21 08:27
> @macrokernel does VAAPI in ffmpeg work for you? something like `ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i INPUT_FILE.mp4 -vf "format=nv12,hwupload" -c:v h264_vaapi OUTPUT_FILE.mp4`? What does `vainfo` return on your device? Maybe also try setting `-hwaccel_device /dev/dri/renderD128` in gyroflow encoder params.
> 
> Some more info here https://trac.ffmpeg.org/wiki/Hardware/VAAPI

Hi, yes, VAAPI seems to be working in ffmpeg, please see the log: 
[ffmpeg_vaapi.log](https://github.com/gyroflow/gyroflow/files/10054616/ffmpeg_vaapi.log)

Here is vainfo: 
[vainfo.txt](https://github.com/gyroflow/gyroflow/files/10054626/vainfo.txt)

Ohh, the latest Gyroflow is working with GPU acceleration! I am getting around 14.6 FPS with H264 and H265. 

![image](https://user-images.githubusercontent.com/9429051/203001778-384af06a-d315-4f60-a3c4-e12badb4b08e.png)

**Comment by AdrianEddy** [comment] 2022-11-21 08:50
> Ohh, the latest Gyroflow is working with GPU acceleration! I am getting around 14.6 FPS with H264 and H265.

Cool, thanks for testing. You can also try selecting `[wgpu] AMD RADV RENOIR (Vulkan)`, it might be a bit faster

**Comment by macrokernel** [comment] 2022-11-21 08:57
> Cool, thanks for testing. You can also try selecting `[wgpu] AMD RADV RENOIR (Vulkan)`, it might be a bit faster

Thanks, `[wgpu] AMD RADV RENOIR (Vulkan)` is doing a bit faster - 15.4 FPS.

**Comment by nightflasher** [comment] 2022-11-21 09:47
this is getting weird: i am now back on stock ubuntu 22.04.1 LTS - no extra ffmpeg nor oibaf graphics drivers.
without the oibaf drivers, i can only select CLOVER AMD...no intel at all. 
after reading and[ comparing my gfx](https://technical.city/en/video/UHD-Graphics-620-vs-Radeon-530) options, it is weirder af: the intel UHD 620 is better than the dedicated amd r7 530 - why would a manufacturer do that? or du i miss something?
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10055262/gyroflow.log)


@macrokernel which drivers did you install?

**Comment by macrokernel** [comment] 2022-11-21 09:51
> @macrokernel which drivers did you install?

Not sure, can you please suggest a way to check the installed drivers? If I remember correct, I am using open source drivers that come with Linux Mint. 
`$ uname -a
Linux magicbook 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
` 
I installed newer ffmpeg from PPA: `http://ppa.launchpad.net/savoury1/ffmpeg4/ubuntu focal main`.

**Comment by AdrianEddy** [comment] 2022-11-21 12:21
@nightflasher please try in latest version, gh899
@macrokernel  and @mituritsyn  please also test gh899 and confirm if all good

**Comment by nightflasher** [comment] 2022-11-21 20:49
Today i had time to install new drivers, so AMD drivers are up to date (again), but it's intel we wanna rock here.
So i've installed new intel gfx drivers, but gyroflow still won't use gpu to render.
[gyroflow_NV12.log](https://github.com/gyroflow/gyroflow/files/10060417/gyroflow_NV12.log)
[gyroflow_P010LE.log](https://github.com/gyroflow/gyroflow/files/10060418/gyroflow_P010LE.log)

**Comment by nightflasher** [comment] 2022-11-21 21:16
tried every option i learned the last days from you and others

**Comment by nightflasher** [comment] 2022-11-21 21:25
i had no error message and rendered was mostly with 10+ fps
but i'm stillt not sure - this could be faster?

![Bildschirmfoto vom 2022-11-21 22-24-16](https://user-images.githubusercontent.com/3342605/203161004-8a7a9a92-ce31-4137-a8fb-e3586e1496d2.png)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10060598/gyroflow.log)

**Comment by AdrianEddy** [comment] 2022-11-21 21:28
hmm that last log file seems to be truncated, did you close gyroflow before uploading the log file?

**Comment by nightflasher** [comment] 2022-11-21 21:47
no...but you will get a new one along with a screenshot
![Bildschirmfoto vom 2022-11-21 22-46-36](https://user-images.githubusercontent.com/3342605/203164541-140e8cf2-e074-4cdd-96a6-15c2e9d228e7.png)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10060809/gyroflow.log)
 right now

**Comment by AdrianEddy** [comment] 2022-11-21 21:49
it's still truncated, you need to close gyroflow after rendering (or you can click Cancel, then close) for log to be properly finished. So far I can see that VAAPI can't be initialized at all with `-hwaccel_device 0`. Try without it

**Comment by nightflasher** [comment] 2022-11-21 21:51
i did, but the log file in the folder is the same, but i've started from comand line and there you go
[gyroflow_rendered_fine.log](https://github.com/gyroflow/gyroflow/files/10060836/gyroflow_rendered_fine.log)

**Comment by nightflasher** [comment] 2022-11-21 21:54
could this one improve the speed?
/etc/sysctl.d/99-i915.conf 
#dev.i915.perf_stream_paranoid = 0

now i've seen NV12
[gyroflow_rendered_fine_nv12.log](https://github.com/gyroflow/gyroflow/files/10060868/gyroflow_rendered_fine_nv12.log)

**Comment by AdrianEddy** [comment] 2022-11-21 21:56
`gyroflow_rendered_fine_nv12.log` looks good and it used VAAPI, how fast did it render?

**Comment by nightflasher** [comment] 2022-11-21 22:18
about 12 fps, still 80+ seconds for a 16 seconds clip - but better than 4-8fps

**Comment by nightflasher** [comment] 2022-11-21 22:19
oh and its HEVC AND H264 compatible

**Comment by AdrianEddy** [comment] 2022-11-21 22:22
well, I think there's nothing else I can do in Gyroflow, looks like it properly initializes and uses VAAPI so the rest is drivers/configuration/flags. You may still try to use the AMD card, I think it will only support H264, I recommend to first try to figure out the flags for command line `ffmpeg` and test there, then try to use these flags in Gyroflow. Good luck!

As 3 people confirmed that VAAPI now works in Gyroflow, I'm closing this issue. Thank you all for testing and providing logs, it was very helpful!

**Closed by AdrianEddy** 2022-11-21 22:22 UTC
Labels: bug, linux

**Comment by jasperges** [comment] 2025-01-04 15:01
For anybody that runs into a similar issue on Fedora (41): to fix it I had to [install the _freeworld_ drivers from RPM Fusion](https://rpmfusion.org/Howto/Multimedia?highlight=(\bCategoryHowto\b)#Hardware_codecs_with_AMD_.28mesa.29):

```sh
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
```

After that GPU encoding worked fine without any extra steps.
