### ISSUE TITLE
Left half only rendered

### ISSUE THREAD

**Issue by Schweizer33** [gyroflow/gyroflow#476] opened 2022-10-09 14:29 UTC
Insta360 GO2 Pro input file.  2880x2880 lens.  Stabilizes fine in Gyroflow v1.3 but the rendered output 2560x1440 only renders the left half, the right side is blank.  Worse in lower res renders.  Same file and lens in v1.2 work fine.  
WIN64

**Comment by AdrianEddy** [comment] 2022-10-09 16:37
Can you please upload gyroflow.log? What system are you using? What's your GPU? Was GPU encoding enabled? I can't reproduce this on Windows.

**Comment by Schweizer33** [comment] 2022-10-09 18:50
AMD Ryzen 5 3400G .  Win10 home. GPU "unchecked".  Log attached.  Thanks. [](url)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/9742341/gyroflow.log)
Sample here: https://youtu.be/Sq3aSGmV5cc

**Comment by AdrianEddy** [comment] 2022-10-09 21:33
Could you please check latest dev build? Should be fixed https://gyroflow.xyz/devbuild/?autodownload

**Closed by AdrianEddy** 2022-10-09 21:33 UTC

**Comment by Schweizer33** [comment] 2022-10-10 09:34
Your fix worked. I tried it with GPU on and off.  Seemed faster too though I only ran a small test clip.  Log attached.  Thanks.  You're amazing and appreciated.  TOM in Minnesota.  
Look how wonderfully your work improves the art of FPV cine.  https://youtu.be/DPJhwcB3GTg
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/9744738/gyroflow.log)
