### ISSUE TITLE
Using gyroflow with a shoulder cam in live streaming

### ISSUE THREAD

**Issue by Milo123459** [gyroflow/gyroflow#664] opened 2023-06-19 15:48 UTC
I've got a black magic camera being used as a shoulder cam. We usually use this when live streaming, but we wanted stable video. Is there a way to use gyroflow in real-time?

**Comment by AdrianEddy** [comment] 2023-06-19 15:50
Currently no, but it will probably be added in the future, more info: https://docs.gyroflow.xyz/app/advanced-usage/live-feed-stabilization
Duplicate of #635

**Closed by AdrianEddy** 2023-06-19 15:50 UTC
