### ISSUE TITLE
Mac M4 Pro no HDR export when using GPU.

### ISSUE THREAD

**Issue by AirKhann** [gyroflow/gyroflow#937] opened 2024-12-13 16:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6

### What operating system are you using?

MacOS 15.2

### What GPU are you using?

M4 Pro

### What happened?

If i export a HLG HDR Gopro 13 video, it doesnt export in HLG HDR until i disable GPU Decoding but with GPU Decoding disabled (rendering over CPU) it takes too long time, why i can't export HLG with GPU Decoding enabled? Is this a bug or am i doing something wrong?

**Comment by AdrianEddy** [comment] 2024-12-13 16:05
HDR is currently not supported, use the plugin for Resolve or Adobe instead
Duplicate of #700

**Closed by AdrianEddy** 2024-12-13 16:05 UTC
Labels: bug
