### ISSUE TITLE
[Bug]: No camera data is transferred when creating the camera profile. fields remain empty.

### ISSUE THREAD

**Issue by Fersy2003** [gyroflow/gyroflow#100] opened 2022-02-06 11:11 UTC
### Gyroflow version

1.0.0 rc1

### What operating system are you using?

Win11

### What GPU are you using?

RTX2080TI

### What happened?

no camera data is transferred when creating the camera profile. fields remain empty.

[____480p_4by3_960x720-60.00fps.zip](https://github.com/gyroflow/gyroflow/files/8010002/____480p_4by3_960x720-60.00fps.zip)

**Comment by AdrianEddy** [comment] 2022-02-06 11:33
Duplicate of #94

**Closed by AdrianEddy** 2022-02-06 11:33 UTC
Labels: bug
