### ISSUE TITLE
adding keyframe : value sometimes not correct

### ISSUE THREAD

**Issue by Ji-flyby** [gyroflow/gyroflow#870] opened 2024-07-30 06:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4 nightly from july 29th

### What operating system are you using?

Mac OS Sonoma 14.5

### What GPU are you using?

M1ultra, M3pro

### What happened?

when adding a keyframe within an allready animated curve, the value the keyframe 'catches' sometimes is not the same as the one displayed in the interface - in this case also the image changes just because of adding keyframe, which implies that the added keyframe value comes from somewhere else..... while the one shown in the interface/slider is correct.

I am usually using 'lock horizont' and some 3D-pitch to look 'deeper'

**Comment by AdrianEddy** [comment] 2024-07-30 06:58
Duplicate of #866

**Closed by AdrianEddy** 2024-07-30 06:58 UTC
Labels: bug
