### ISSUE TITLE
Latest build (1.3) not running on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by softwarelifecycle** [gyroflow/gyroflow#497] opened 2022-11-07 05:21 UTC
Hello all:
My preferred OS is Ubuntu and the only thing that I need in my sweet of tools that doesn't work on it is Gyroflow.
It works fine on Windows....but I do not like windows!

I downloaded the Gyroflow-linux64.Appimage and upon running all it does is produce a .dmp file...
For the prior version of Gyroflow, I followed these instructions:
https://github.com/gyroflow/gyroflow/issues/154#:~:text=I%20can%20confirm%20that%20following%20the%20steps%20linked
And they worked... but they do not work for the latest 1.3 build.

This should not be so difficult... Are there any other approaches that work? Can the dmp file be uploaded here?

Thanks
Harry

**Comment by AdrianEddy** [comment] 2022-11-07 18:10
Use latest dev build and use .tar.gz package instead of .AppImage: https://gyroflow.xyz/devbuild/?autodownload

**Comment by angus-elsa** [comment] 2022-11-07 19:53
1.3 not working on 20.04 either.

**Comment by AdrianEddy** [comment] 2022-11-07 19:59
> 1.3 not working on 20.04 either.

did you check the latest dev build from the link I provided?

**Comment by AdrianEddy** [comment] 2022-11-08 03:01
Duplicate of #478

**Closed by AdrianEddy** 2022-11-08 03:01 UTC

**Comment by angus-elsa** [comment] 2022-11-08 07:18
> > 1.3 not working on 20.04 either.
> 
> did you check the latest dev build from the link I provided?

Worked perfectly my friend, cheers buddy
