### ISSUE TITLE
Would love if Gyroflow could use gyro, accelerometer etc. from OpenCamera-Sensors (On Github)

### ISSUE THREAD

**Issue by Slint7** [gyroflow/gyroflow#370] opened 2022-06-05 12:55 UTC
### Is there an existing feature request for this?

- [ ] I have searched the existing requests

### Description

I would like to stabilize videos taken with my Android phone.

For Open-Camera on Android, there is an extension called OpenCamera-Sensors.(https://github.com/MobileRoboticsSkoltech/OpenCamera-Sensors)
OpenCamera-Sensors records gyro, accelerometer, and other data and creates .csv files for videos taken with Open-Camera.

Would love it if you could support this format or provide an alternative solution to stabilize Android phone footage?

Alternatively, do you know how I could convert the .csv sensor data into a format that is supported by Gyroflow?

I have attached the file with the sensor data, however, could not attach the video due to file size limitations.

[20220521_111301.zip](https://github.com/gyroflow/gyroflow/files/8839990/20220521_111301.zip)

**Comment by AdrianEddy** [comment] 2022-06-05 14:17
Duplicate of #312

**Closed by AdrianEddy** 2022-06-05 14:17 UTC
Labels: enhancement
